[workspace]

members = [
    "atlasserver",
    "atlas_ads",
    "atlas_apple_server_notify",
    "atlas_broadcast",
    "atlas_dynamo",
    "atlas_iap",
    "atlas_pubsub",
    "atlas_push",
    "atlas_sso",
]